services:

  audio:
    image: skafzal04/echogen-backend:latest
    container_name: ecogen-backend
    ports:
      - "8000:8000"
    env_file:
      - ./audio/.env
    restart: always

  frontend:
    image: yourdockerhubusername/echogen-frontend:latest
    container_name: ecogen-frontend
    ports:
      - "3000:80"
    depends_on:
      - audio
    restart: always
